import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

// USER_CODE_MARKER

class ListNode {
    int val;
    ListNode next;
    ListNode(int x) { val = x; }
}

class TreeNode {
    int val;
    TreeNode left;
    TreeNode right;
    TreeNode(int x) { val = x; }
}

public class {{CLASS_NAME}} {
    private static final String COMPARE_MODE = "{{COMPARE_MODE}}";
    private static final Gson gson = new GsonBuilder()
        .registerTypeAdapter(TreeNode.class, new TreeNodeSerializer())
        .registerTypeAdapter(ListNode.class, new ListNodeSerializer())
        .serializeSpecialFloatingPointValues()
        .create();

    public static void main(String[] args) {
        String testsJsonString = "{{TESTS_JSON}}";
        JsonArray testCasesArray = JsonParser.parseString(testsJsonString).getAsJsonArray();
        List<TestResult> results = new ArrayList<>();

        for (int i = 0; i < testCasesArray.size(); i++) {
            JsonObject testCase = testCasesArray.get(i).getAsJsonObject();
            JsonArray inputArgs = testCase.getAsJsonArray("input");
            JsonElement expectedOutput = testCase.get("expectedOutput");

            try {
                // This part needs to be dynamically generated by the Go service
                Object output = {{FUNCTION_CALL_LINE}}; 

                JsonElement normalizedOutput = normalize(output, new HashSet<>());
                JsonElement normalizedExpected = normalize(expectedOutput, new HashSet<>());

                boolean isCorrect = deepEqual(normalizedOutput, normalizedExpected);
                TestResult result = new TestResult(i + 1, isCorrect, truncate(normalizedOutput), truncate(normalizedExpected));
                if (!isCorrect) {
                    result.setDiff(diffSummary(normalizedOutput, normalizedExpected));
                }
                results.add(result);

            } catch (Exception e) {
                TestResult result = new TestResult(i + 1, false, null, truncate(expectedOutput));
                result.setError(e.toString());
                results.add(result);
            }
        }

        Summary summary = new Summary("finished", results);
        System.out.println(gson.toJson(summary));
    }
    
    private static JsonElement normalize(Object value, Set<Object> visited) {
        if (value == null) return null;
        if (visited.contains(value)) return new JsonPrimitive("[Circular]");
        
        if (value instanceof JsonElement) {
            // Assuming JSON elements from test cases are already in a normalized-like format
            return (JsonElement) value;
        }

        visited.add(value);

        if (value instanceof ListNode) {
            JsonObject obj = new JsonObject();
            obj.addProperty("__type", "LinkedList");
            JsonArray values = new JsonArray();
            ListNode curr = (ListNode) value;
            while(curr != null) {
                values.add(curr.val);
                curr = curr.next;
            }
            obj.add("values", values);
            return obj;
        }

        if (value instanceof TreeNode) {
             return gson.toJsonTree(value); // Use the custom serializer
        }
        
        if (value instanceof List) {
            JsonArray array = new JsonArray();
            for(Object item : (List<?>) value) {
                array.add(normalize(item, visited));
            }
            return array;
        }

        if (value instanceof Map) {
            JsonObject obj = new JsonObject();
            List<String> keys = ((Map<String, ?>) value).keySet().stream().sorted().collect(Collectors.toList());
            for(String key : keys) {
                 obj.add(key, normalize(((Map<?, ?>) value).get(key), visited));
            }
            return obj;
        }
        
        visited.remove(value); // Not a container, remove from visited
        return gson.toJsonTree(value);
    }

    private static boolean deepEqual(JsonElement a, JsonElement b) {
        double epsilon = 1e-6;
        if (a == null || b == null) return a == b;
        if (a.isJsonNull() || b.isJsonNull()) return a.isJsonNull() && b.isJsonNull();

        switch (COMPARE_MODE) {
            case "STRICT":
                return a.equals(b);
            case "APPROX":
                if (!a.isJsonPrimitive() || !b.isJsonPrimitive() || !((JsonPrimitive)a).isNumber() || !((JsonPrimitive)b).isNumber()) return false;
                double da = a.getAsDouble();
                double db = b.getAsDouble();
                return Math.abs(da - db) < epsilon * Math.max(1, Math.max(Math.abs(da), Math.abs(db)));
            case "TEXT":
                String sa = a.isJsonPrimitive() ? a.getAsString().trim().replaceAll("\s+", " ") : gson.toJson(a);
                String sb = b.isJsonPrimitive() ? b.getAsString().trim().replaceAll("\s+", " ") : gson.toJson(b);
                return sa.equals(sb);
            case "ORDER_INSENSITIVE":
                 if (!a.isJsonArray() || !b.isJsonArray()) return false;
                 JsonArray arrA = a.getAsJsonArray();
                 JsonArray arrB = b.getAsJsonArray();
                 if (arrA.size() != arrB.size()) return false;
                 List<JsonElement> listA = StreamSupport.stream(arrA.spliterator(), false).collect(Collectors.toList());
                 List<JsonElement> listB = StreamSupport.stream(arrB.spliterator(), false).collect(Collectors.toList());
                 // This is a simplification. A robust sort for JSON elements is non-trivial
                 try {
                    listA.sort((e1, e2) -> gson.toJson(e1).compareTo(gson.toJson(e2)));
                    listB.sort((e1, e2) -> gson.toJson(e1).compareTo(gson.toJson(e2)));
                 } catch(Exception e) {
                     return false; // Cannot sort complex objects easily
                 }
                 return deepEqual(gson.toJsonTree(listA), gson.toJsonTree(listB));
            default: // STRUCTURAL
                return structuralDeepEqual(a, b, epsilon);
        }
    }

    private static boolean structuralDeepEqual(JsonElement a, JsonElement b, double epsilon) {
        if (a == null || b == null) return a == b;
        if (a.isJsonNull() || b.isJsonNull()) return a.isJsonNull() && b.isJsonNull();
        if (a.isJsonPrimitive() && b.isJsonPrimitive()) {
            if (((JsonPrimitive)a).isNumber() && ((JsonPrimitive)b).isNumber()) {
                 double da = a.getAsDouble();
                 double db = b.getAsDouble();
                 return Math.abs(da - db) < epsilon * Math.max(1, Math.max(Math.abs(da), Math.abs(db)));
            }
            return a.equals(b);
        }
        if (a.isJsonArray() && b.isJsonArray()) {
            JsonArray arrA = a.getAsJsonArray();
            JsonArray arrB = b.getAsJsonArray();
            if (arrA.size() != arrB.size()) return false;
            for (int i = 0; i < arrA.size(); i++) {
                if (!structuralDeepEqual(arrA.get(i), arrB.get(i), epsilon)) return false;
            }
            return true;
        }
        if (a.isJsonObject() && b.isJsonObject()) {
            JsonObject objA = a.getAsJsonObject();
            JsonObject objB = b.getAsJsonObject();
            if (objA.size() != objB.size()) return false;
            List<String> keysA = objA.keySet().stream().sorted().collect(Collectors.toList());
            List<String> keysB = objB.keySet().stream().sorted().collect(Collectors.toList());
            if(!keysA.equals(keysB)) return false;

            for (String key : keysA) {
                if (!structuralDeepEqual(objA.get(key), objB.get(key), epsilon)) return false;
            }
            return true;
        }
        return false;
    }
    
    private static String diffSummary(JsonElement actual, JsonElement expected) {
        if (actual.isJsonArray() && expected.isJsonArray()) {
            JsonArray arrA = actual.getAsJsonArray();
            JsonArray arrB = expected.getAsJsonArray();
            if (arrA.size() != arrB.size()) {
                return "Array length mismatch: expected " + arrB.size() + ", got " + arrA.size();
            }
            for (int i = 0; i < arrB.size(); i++) {
                if (!deepEqual(arrA.get(i), arrB.get(i))) {
                    return "Mismatch at index " + i + ": expected " + truncate(arrB.get(i)) + ", got " + truncate(arrA.get(i));
                }
            }
        }
         if (actual.isJsonObject() && expected.isJsonObject()) {
            JsonObject objA = actual.getAsJsonObject();
            JsonObject objB = expected.getAsJsonObject();
            Set<String> keysA = objA.keySet();
            Set<String> keysB = objB.keySet();
            if(!keysA.equals(keysB)){
                Set<String> missing = new HashSet<>(keysB); missing.removeAll(keysA);
                Set<String> extra = new HashSet<>(keysA); extra.removeAll(keysB);
                String msg = "";
                if(!missing.isEmpty()) msg += "Missing keys: " + missing;
                if(!extra.isEmpty()) msg += " Extra keys: " + extra;
                return msg.trim();
            }
            for(String key : keysB){
                 if (!deepEqual(objA.get(key), objB.get(key))) {
                    return "Mismatch at key '" + key + "': expected " + truncate(objB.get(key)) + ", got " + truncate(objA.get(key));
                }
            }
        }
        return "Values differ: expected " + truncate(expected) + ", got " + truncate(actual);
    }

    private static JsonElement truncate(JsonElement element) {
        String s = gson.toJson(element);
        if (s.length() > 2000) {
            return new JsonPrimitive(s.substring(0, 2000) + "...(truncated)");
        }
        return element;
    }
}

class TestResult {
    int test;
    boolean ok;
    JsonElement output;
    JsonElement expected;
    String error;
    String diff;

    TestResult(int test, boolean ok, JsonElement output, JsonElement expected) {
        this.test = test;
        this.ok = ok;
        this.output = output;
        this.expected = expected;
    }

    public void setError(String error) { this.error = error; }
    public void setDiff(String diff) { this.diff = diff; }
}

class Summary {
    String status;
    long passed;
    long total;
    List<TestResult> details;

    Summary(String status, List<TestResult> results) {
        this.status = status;
        this.details = results;
        this.total = results.size();
        this.passed = results.stream().filter(r -> r.ok).count();
    }
}

// Custom Serializers for special data structures
class TreeNodeSerializer implements JsonSerializer<TreeNode> {
    @Override
    public JsonElement serialize(TreeNode src, Type typeOfSrc, JsonSerializationContext context) {
        return serialize(src, new HashSet<>());
    }
    private JsonElement serialize(TreeNode src, Set<TreeNode> visited) {
        if (src == null) return null;
        if (visited.contains(src)) return new JsonPrimitive("[Circular]");
        visited.add(src);

        JsonObject obj = new JsonObject();
        obj.addProperty("__type", "TreeNode");
        obj.addProperty("val", src.val);
        obj.add("left", serialize(src.left, visited));
        obj.add("right", serialize(src.right, visited));
        
        visited.remove(src);
        return obj;
    }
}

class ListNodeSerializer implements JsonSerializer<ListNode> {
    @Override
    public JsonElement serialize(ListNode src, Type typeOfSrc, JsonSerializationContext context) {
        JsonObject obj = new JsonObject();
        obj.addProperty("__type", "LinkedList");
        JsonArray values = new JsonArray();
        ListNode curr = src;
        while(curr != null) {
            values.add(curr.val);
            curr = curr.next;
        }
        obj.add("values", values);
        return obj;
    }
}